### ISSUE TITLE
Any plans to update this to work with the new Twitter API?

### ISSUE THREAD

**Issue by rodrigoalcarazdelaosa** [hyperbolicbr/jquery.socialstats#3]
I'm looking into a way of _reading_ the number of likes of a given tweet and writing that number inside a `span` in my webpage. I think this script would be perfect for what I need.

Thank you very much in advance,

Rodrigo

**Comment by fboldo** [comment]
> I'm looking into a way of _reading_ the number of likes of a given tweet and writing that number inside a `span` in my webpage. I think this script would be perfect for what I need.
> 
> Thank you very much in advance,
> 
> Rodrigo

Hi Rodrigo,

The jquery.socialstats is an old and dead repo, so no updates are planned.

Maybe some of these packages can help, https://www.npmjs.com/search?q=keywords%3Atwitter%20count

**Comment by rodrigoalcarazdelaosa** [comment]
Unfortunately all the packages I've found have been published years ago, long before the new API. I'll wait...
